### ISSUE TITLE
Find better example code for move semantics.

### ISSUE THREAD

**Issue by hageboeck** [hsf-training/cpluspluscourse#106]
And copy elision will take care of `MyVector` ...
Maybe we should think about something for the future.

_Originally posted by @hageboeck in https://github.com/hsf-training/cpluspluscourse/pull/103#discussion_r822684920_

The problem is that all the code we suggest will get optimised. We should come up with something that really improves only with move semantics.

**Comment by bernhardmgruber** [comment]
As I said in the comments, NRVO is not guaranteed:

```c++
A f() {
  A a;
  ...
  return a; // return optimization not guaranteed
}
```

From personal experience, debug builds will pull a copy of `A` when returning. Move operations can make this cheaper. Release builds don't care, they usually optimize.

**Comment by bernhardmgruber** [comment]
Still, please fix this! :)
