### ISSUE TITLE
CMake and/or vanilla make ?

### ISSUE THREAD

**Issue by chavid** [hsf-training/cpluspluscourse#118]
@all Is there an agreement that CMake should be mandatory for the exercices ? If so, the old files `Makefile` should be removed from git.

**Comment by chavid** [comment]
Ouch... Attila has worked hard, perhaps making this issue obsolete...

**Comment by hageboeck** [comment]
Both are fine for me. But we should explain the advantages/disadvantages.

**Comment by bernhardmgruber** [comment]
I created a ticket for CMake now since I also think we should talk briefly on CMake: #123
