### ISSUE TITLE
Move the Fraction exercise at the end of OO

### ISSUE THREAD

**Issue by chavid** [hsf-training/cpluspluscourse#134]
I think you will all agree the operator exercise, in its current content, would be better placed at the end of the OO exercises. Also, if its aim is focused on operators, I would initially provide the basic implementation of Fraction, including the normalization stuff.

**Comment by bernhardmgruber** [comment]
The operators exercise is at the end of the OO: https://github.com/hsf-training/cpluspluscourse/blob/master/code/ExercisesCheatSheet_All.md. It seems to be in the wrong place in the essential cheat sheet: https://github.com/hsf-training/cpluspluscourse/blob/master/code/ExercisesCheatSheet_TheEssentials.md
