### ISSUE TITLE
Add a few slides on further resources

### ISSUE THREAD

**Issue by bernhardmgruber** [hsf-training/cpluspluscourse#135]
@amadio suggest to me again, and I also have thought about that, that we should add more pointers to external resources. We have the occasional link to cppreference and I also linked CppCon talks in a couple of places. But there is so much more material available.

Like:
* the youtube channels of various conferences, e.g. cppcon, meeting c++, etc.
* youtube channels of dedicated C++ trainers, e.g. Jason Turner's C++ weekly: https://www.youtube.com/c/lefticus1
* CppCast: https://cppcast.com/
* Books! I am sure everyone has their favorite recommendation, like Effective Modern C++, A Tour of C++, Templates: The complete guide (:D). @amadio also pointed out to me that CERN has [free access](https://www.oreilly.com/library/view/temporary-access/) to books on O'Reilly, where we can find a lot of C++ resources.
* links to awesome C++ libraries: https://github.com/fffaraz/awesome-cpp
* the ISO C++ FAQ: https://isocpp.org/wiki/faq
* from @krasznaa: https://cmake.org/cmake/help/latest/guide/tutorial/index.html

We should add a few slides or even a tiny chapter at the end with further resources to explore for interested students.

**Comment by amadio** [comment]
> amadio suggest to me again, and I also have thought about that, that we should add more pointers to external resources.

My original suggestion was to give people more pointers for further reading and link to popular YouTube channels. I think that after my second pull request (#383) is merged, this could be closed.
