### ISSUE TITLE
Add a slide on nm, ldd and objdump

### ISSUE THREAD

**Issue by bernhardmgruber** [hsf-training/cpluspluscourse#145]
Both tools are mentioned in the exercise on the compilation chain, but we have no slide that mentions what these tools do and why/when they are needed.

**Comment by bernhardmgruber** [comment]
I would still like to have a slide or two on these. I know @sponce explains that as part of an exercise, so we do not need to present  the slides. But they can still serve as a summary and just list the few commands that were shown during the exercise. @sponce or @hageboeck may I assign one of you to this issue?

**Comment by sponce** [comment]
Fine with me (both the idea and the assignment).

**Comment by bernhardmgruber** [comment]
@hageboeck presented these tools again today with several flags. I could never do that, I just would not know the flags. Please add one slide on that :)
