### ISSUE TITLE
Github action built PDF different than local one

### ISSUE THREAD

**Issue by bernhardmgruber** [hsf-training/cpluspluscourse#153]
I just saw that the PDF built by the Github actions is slighly different from the one I build locally. Also the size is quite different.

E.g. Github action:
![image](https://user-images.githubusercontent.com/1224051/158764576-9066b17a-e01a-488f-8561-0d224a6fcd3a.png)
Size: 2.5MiB

built locally (Windows/MikTex):
![image](https://user-images.githubusercontent.com/1224051/158764667-686bb796-02de-4efc-b946-4ababaefe622.png)
Size: 5.0MiB

Could we please fix the GitHub action so it builds a visually correct PDF?

**Comment by klieret** [comment]
Hmm, maybe the pdf produced by gh actions doesn't have the fonts embedded or some trouble related to that? 

But I wouldn't say that either of them is "correct" or "wrong". 

I also don't have any ideas about that. Can you add someone who might help here?

Otherwise I vote to close.

**Comment by bernhardmgruber** [comment]
Let's wait until #184 is merged and then check the slides again. Those need to be proper.

**Comment by bernhardmgruber** [comment]
We concluded the slides from GitHub actions are fine.
