### ISSUE TITLE
Add slides on `<random>`

### ISSUE THREAD

**Issue by bernhardmgruber** [hsf-training/cpluspluscourse#254]
So far we do not discuss random number generation. We use it a lot in the exercises though. We should add a few slides explaining engines and distribution. And to not use `rand()` anymore.

**Comment by chavid** [comment]
Some inspiration if you want : https://github.com/chavid/ModernScientificCpp/blob/main/5-ClassRoom/3-FloatingPointComputing/3-random-numbers.ipynb . I let you the fight with the conversion to latex ;)

**Comment by bernhardmgruber** [comment]
This is awesome!
