### ISSUE TITLE
Consider removing second python example in lambda section

### ISSUE THREAD

**Issue by bernhardmgruber** [hsf-training/cpluspluscourse#256]
I'm fine with the first Python analogy. That's indeed helpful for people who know it already. But the second one about capture only shows that there's nothing specific to be done in Python. Here I don't see how it helps, because the message is:
In C++ it's different than in Python.

_Originally posted by @hageboeck in https://github.com/hsf-training/cpluspluscourse/pull/250#discussion_r953685189_

**Comment by bernhardmgruber** [comment]
This is about this slide:
![image](https://user-images.githubusercontent.com/1224051/186419244-98061574-f31c-4c39-94c2-652594c00d70.png)

**Comment by hageboeck** [comment]
Instead, one could use the space of the first box for some kind of explanation like:
- Task: Write a functor to increment values in a collection
- How do you avoid writing one lambda for every possible value of `increment`?
- `increment` needs to be "captured"
