### ISSUE TITLE
Create a table of contents / cheat sheet to run the exercises for the advanced course

### ISSUE THREAD

**Issue by hageboeck** [hsf-training/cpluspluscourse#265]
# Day 1
- hello
- operators
- move
- gdb exercise

# Day 2
- smart ptr
- optional
- variant
- templates (ordered vector)
- (optional) asan

# Day 3
- atomic
- race
- templates if not done on day 2
- variadic templates
- <=>
- concepts

**Comment by sponce** [comment]
Addressed in #306 to be merged very soon so closing
