### ISSUE TITLE
Question on ADL consequence slide

### ISSUE THREAD

**Issue by bernhardmgruber** [hsf-training/cpluspluscourse#287]
In the section on ADL, we have this slide:
![image](https://user-images.githubusercontent.com/1224051/193033577-ecc459c2-8817-4fbc-ba99-2f24acede2d5.png)

I don't get what this recommendation has to do with ADL. Can someone explain this to me please?

**Comment by bernhardmgruber** [comment]
@sponce, any idea?

**Comment by sponce** [comment]
Not really. I also do not see the relation with ADL just like this...

**Comment by bernhardmgruber** [comment]
Hmm. I was wondering whether it meant something like: If you want to add functionality to a framework, implement this functionality inside the namespaces of the framework.

If it's about using a framework with namespaces, I don't see a problem with the `using namespace MyProject`.

**Comment by bernhardmgruber** [comment]
I propose to remove the slide: #316

**Comment by bernhardmgruber** [comment]
@hageboeck or @chavid, do you know what this slide was intended to convey?

**Comment by chavid** [comment]
No idea where this comes from.
