### ISSUE TITLE
Move exercise too complicated

### ISSUE THREAD

**Issue by hageboeck** [hsf-training/cpluspluscourse#340]
Comment by a participant: "You can't see the wood for the tree"

There's more templates and complications than needs to be to demonstrate moving.

**Comment by chavid** [comment]
+1. NVector is uselessly complete. On the other hand, one can wonder why we shuffle the global std::vector, which only contains empty NVectors... The exercise has probably a long history, and would benefit from a global review ;)

**Comment by hageboeck** [comment]
One more thing: In the advanced course, we did this before the tools. We don't discuss profilers, though.
