### ISSUE TITLE
Add move notice to previous repository

### ISSUE THREAD

**Issue by klieret** [hsf-training/cpluspluscourse#38]
Hi @sponce : Could you add a quick move notice to https://gitlab.cern.ch/sponce/cpluspluscourse/ so that people who still have the old link end up here?

**Comment by sponce** [comment]
Yes, sure. I'll "close" it and redirect.

**Comment by sponce** [comment]
I've archived the project, changed the title to "C++ course - outdated", changed the description to points here and added a readme pointing here. Should be enough :-)
