### ISSUE TITLE
On page 88  C++Course_full.pdf there is void (incorrect) return type of MyFirstClass::sum  void MyFirstClass::sum(int b) {return a + b;}

### ISSUE THREAD

**Issue by lvdpower** [hsf-training/cpluspluscourse#385]
<details>
<summary><strong>On page 88  C++Course_full.pdf there is void (incorrect) return type of MyFirstClass::sum</strong></summary>

On page 88  C++Course_full.pdf there in void (incorrect) return type of MyFirstClass::sum  void MyFirstClass::sum(int b) {return a + b;}

But on page 89 there is correct one. (int)

\- HSF Training
</details>

**Comment by hageboeck** [comment]
Thanks for letting us know! Well spotted!
