### ISSUE TITLE
Beginner Course - Debugging

### ISSUE THREAD

**Issue by TobiasDuswald** [hsf-training/cpluspluscourse#394]
Dear all,

I wanted to follow up on a brief conversation I had with @roiser regarding debugging tools. First of all, I think it's great that it's part of your beginner track because I often see this topic being ignored while, in fact, it's one of the most important topics there is. I reached out to @roiser to "advertise" the graphical debuggers. It seems like over time people fell back to using gdb / lldb via the terminal, but there are arguably many advantages to using GUIs for debugging. E.g., [CodeLLDB](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb) is a free extension for VSCode integrating debugging of CPP code in the IDE. There are many alternatives (see for instance [ATPESC2022](https://extremecomputingtraining.anl.gov/agenda-2022/), Track 6) but some of them are not free.

Point of this issue is that I think it would be very helpful to make people aware of these tools such that they at least know they exist and can follow up if they wanted to. So I think it would be good to consider allocating 1-2 slides to expose participants to these tools. :) 

Tobias

**Comment by bernhardmgruber** [comment]
Hi, thank you for your suggestion!

> It seems like over time people fell back to using gdb / lldb via the terminal, but there are arguably many advantages to using GUIs for debugging.

In my experience this depends a lot on your organisation's culture. For many software engineers or folks in the industry using a graphical IDE is a no-brainer. Others just start out with the bare and established command line tools and manage to pass the long learning curve to also reach stunning productivity. It is ultimately a mix of culture, education, work environment and personal preference.

> [...] but some of them are not free.

Which is often a big driver for choosing a specific solution. A few hundret bucks sounds expensive, especially when you are a student or in your early career. However, when you start to think about the value of your own time, a good development environment can already amortize its cost at the first bug that took you only half the time to find :)

CERN has licenses for some products, like MS Visual Studio which offers a great experience on Windows. Your question now motivated me to inquire at the license service whether CERN could get licenses for CLion, which I have been using for 2 years now on Linux and also offers a great experience.

> Point of this issue is that I think it would be very helpful to make people aware of these tools such that they at least know they exist and can follow up if they wanted to. So I think it would be good to consider allocating 1-2 slides to expose participants to these tools. :)

Very much agreed! But I am only one voice on this course and people may have different opinions. It would help if you could suggest some concreate products, maybe even with a few key points that makes the product great. Like you suggested `CodeLLDB`, which I have not heard before. I know VS Code has a debugger, but I have never used it (I use CLion) so i don't know whether `CodeLLDB` provides a benefit over the built-in debugger. Maybe someone will then try said product and if they are convinced as well, we could put it on a slide.

**Comment by bernhardmgruber** [comment]
>  Your question now motivated me to inquire at the license service whether CERN could get licenses for CLion

So, the CERN license service informed me that we have a pooled license for JetBrains products at a reduced price. But you cannot use it for free, your group would need to contribute to the license costs. The license service can inform you about all the details in case you are interested.

**Comment by roiser** [comment]
Very good, is there already a pointer to it in our slides? If not shall we provide one?

**Comment by bernhardmgruber** [comment]
I can add a slide when preparing for the next HEP C++ coures. I am busy the next two weeks.

@TobiasDuswald please add some more concrete tools you would like to see on the slides. I can then include them when I make the slide.

**Comment by eguiraud** [comment]
Runaway comment: I'm a big fan of https://github.com/cyrus-and/gdb-dashboard to give gdb a boost. The one big thing gdb-dashboard doesn't provide is that it won't move your editor's cursor to the line currently being debugged (it will _display_ it nicely and with syntax highlighting, but it can't do anything for your editor).

**Comment by ikabadzhov** [comment]
Hi, I recently picked an alternative - https://github.com/hugsy/gef. The main reason I prefer it to Cyrus's dashboard: after moving to another line (i.e. `next`), the Cyrus' dashboard flushes the screen and I cannot see the previous state ... whereas Gef would give the result below the previous. On top of that Gef comes with a slightly more fancy coloring scheme - different color for Modified register | Code | Heap | Stack | String. Lastly, it is said to be "easily extensible", allowing to create own commands - https://hugsy.github.io/gef/api/ (I have not tried them yet though).
Problem with cursor is still there.
