### ISSUE TITLE
Better example for init-statements in range-for

### ISSUE THREAD

**Issue by bernhardmgruber** [hsf-training/cpluspluscourse#398]
When browsing through the slides, I extended this slide with the C++23 version:
![image](https://user-images.githubusercontent.com/1224051/218997815-8971c3b2-7c0d-43c3-b163-2fcf160e80f2.png)
Because you should not write a for-each loop and count your index manually. However, this is still the basics chapter so using `std::views::enumerate` may be a bit too much here. So I wondered what other example I could show. The [paper](https://wg21.link/P0614) for the feature shows:
```c++
for (T thing = f(); auto& x : thing.items()) {
  mutate(&x);
  log(x);
}
```
and claims that `for (auto& x : f().items())` is wrong, if `f()` returns a temporary. However, that was also fixed in C++23 by extending the lifetime of all temporaries in the for-loop head. So I wonder what usecases remain for the range-for with init statements. Any ideas?

**Comment by bernhardmgruber** [comment]
Turns out ChatGPT does not have a better use case either. I also considered a lock that is held for the duration of the for loop.

**Comment by hageboeck** [comment]
A lock is a valid use case. Otherwise, I can only think of "accumulators" that are more complicated than just `enumerate`. But these you can always express in other ways, or you just put the entire loop including your lock or accumulators in a scope.

Looks like the feature only exists to make the for-loop behave in the same way as `if` and the like?

**Comment by bernhardmgruber** [comment]
> A lock is a valid use case. 

That actually sounds useful!

> Looks like the feature only exists to make the for-loop behave in the same way as `if` and the like?

I honestly think so as well.

So in the end, maybe let's just leave the slide as is.
