### ISSUE TITLE
Use and present godbolt

### ISSUE THREAD

**Issue by sponce** [hsf-training/cpluspluscourse#40]
Godbolt should be mentioned and presented in the tools section.
And every code example should ideally have a link to a godbolt page with the code compiling there.

**Comment by sponce** [comment]
during KCacheGrind exercise, compiler was smart enough to precompute sqrt(5): we could use godbolt.org as ways to look at the assembly

**Comment by valassi** [comment]
Suggestion by Sebastien today
- Slides to present godbolt and how to use
- Much more ambitious (and later) goal, have godbolt links for ALL examples we present in the slides

**Comment by bernhardmgruber** [comment]
Here is a crazy idea: generate the godbolt link automatically via a latex command ;) I suspect godbolt supports passing the code via an URL. We could build that URL in latex. But maybe this is an overkill.

**Comment by sponce** [comment]
:-) I like the idea. But in practice I fear that what we put on slides is missing some boiler plate code that will need to be there in godbolt, so it may be less easy than a direct "copy-paste"

**Comment by valassi** [comment]
Hi, yesterday I was looking at various options too. Some facts and recent developments (I can attach links)

- there is an API (maybe this is what Manfred means?), rest and non rest, to upload snippets of code (https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/API.md)

- there is now a way to include code from github (issue 1442 in https://github.com/compiler-explorer/compiler-explorer), but I am not sure this would help us for the c++ course, see an example from that issue https://godbolt.org/z/AXAe8K

- there is now a way to upload even large projects with several files (this is for info beyond the c++ course, maybe you were using it already?), but my impression is that it all must be done manually and again maybe not very useful for the c++ course? (August 2021, https://www.reddit.com/r/cpp/comments/pcrg7j/compiler_explorer_now_supports_multiple_file/)

**Comment by bernhardmgruber** [comment]
CppCon 2021 talk on "Just Enough Assembly for Compiler Explorer": https://www.youtube.com/watch?v=_sSFtJwgVYQ

**Comment by roiser** [comment]
Hi, 

I was thinking about if we could easily fix and eventually swap compilers when needed. One way of doing this could be to write the example in godbolt and then share a "full link" this way the source code and many options are included right in the URL, e.g. this is the hello world 

``` 
https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:20,endLineNumber:1,positionColumn:20,positionLineNumber:1,selectionStartColumn:20,selectionStartLineNumber:1,startColumn:20,startLineNumber:1),source:'%23include+%3Ciostream%3E%0A%0Aint+main()+%7B%0A++++std::cout+%3C%3C+%22Hello+World%22+%3C%3C+std::endl%3B%0A++++return+0%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g121,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'1',directives:'0',execute:'0',intel:'1',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x86-64+gcc+12.1+(C%2B%2B,+Editor+%231,+Compiler+%231)',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4
```

in the URL there are two strings ```compiler:g121``` and ```x86-64+gcc+12.1``` which is the  we should change in case. 

Alternatively we can use always "gcc (trunk)" but not sure we really want to do that?

**Comment by sponce** [comment]
I've now added a couple of slides for a very quick introduction to godbolt (#232). The later goal of using it seems a little bit too ambitious according to the discussions here, so I would forget about it for the moment.
