### ISSUE TITLE
Add pointer to other HSF courses

### ISSUE THREAD

**Issue by sponce** [hsf-training/cpluspluscourse#44]
In particular in the tool section, e.g. git, cmake, ...

**Comment by sponce** [comment]
Sure. HSF has a number of courses available on different topics that we touch very quickly in the course, in particular in the tools section. The full list is at https://hepsoftwarefoundation.org/training/curriculum.html

The idea is to simply add pointers to the relevant courses at the end of each part, e.g. after the crash course to git point to the git course, etc...

**Comment by klieret** [comment]
We could also include something like the banner [here](https://hsf-training.github.io/hsf-training-docker/index.html) somewhere.

**Comment by roiser** [comment]
done in #109
