### ISSUE TITLE
About constness exercise

### ISSUE THREAD

**Issue by chavid** [hsf-training/cpluspluscourse#452]
After the step about pointers, and before the step about const members, I would add a step with functions and references, similar to the one with pointers. Just to emphasize that problems with pointers are exactly the same with references. When the students directly jump from "functions with pointer arguments" to "class methods with reference arguments", they make wrong assumptions. Evene more, we should find a way to emphasize the role of the implicit this in this story.

**Comment by hageboeck** [comment]
Hello @chavid,

thanks, that's a good idea! Could you review the corresponding PR #510, please?
