### ISSUE TITLE
Rename the `code` directory to `exercises`

### ISSUE THREAD

**Issue by bernhardmgruber** [hsf-training/cpluspluscourse#456]
I always have a 4 second brain hang when I try to find the exercises folder because `code` just sounds too generic. I propose to rename the folder to `exercises`. Any objections?

**Comment by bernhardmgruber** [comment]
Just happended again. @sponce and @hageboeck, what do you think?

**Comment by sponce** [comment]
I do not care. Just remember you have to change ALL places where this is referred to. Please git grep
