### ISSUE TITLE
Proposal on how to split the course into a basic and advanced course. 

### ISSUE THREAD

**Issue by roiser** [hsf-training/cpluspluscourse#46]
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution.
To ensure that the right people get notified, you can tag some of the last
contributors with `@githubname`.

Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact the HSF training convenors ([contacts here](https://hepsoftwarefoundation.org/workinggroups/training.html)).

You may delete these instructions from your issue.

\- HSF Training
</details>

**Comment by sponce** [comment]
So I would propose 3 days of Basic  course and initially 2 days of advanced one, growing to 3 with C++ 20.

Content of the Basic course : 
===

Day 1
---
History and goals
 - History
 - Why we use it ?

Language basics
 - Core syntax and types
 - Arrays and Pointers
 - Compound data types
 - References
 - Functions
 - Operators
 - Scopes / namespaces
 - Control instructions
 - Headers and interfaces
 - Auto keyword

Day 2
---

Useful tools
 - C ++ editor
 - Code management
 - Code formatting
 - The Compiling Chain
 - Debugging

Object orientation (OO)
 - Objects and Classes
 - Inheritance
 - Constructors/destructors

Day 3
---
Static members
 - Allocating objects
 - Advanced OO
 - Operators
 - Functors

Core modern C ++
 - Constness
 - Exceptions
 - Templates
 - The STL
 - Lambdas
 - pointers and RAII

Advanced Course
===

Object orientation (OO)
 - Name Lookups

Core modern C ++
 - Constant Expressions
 - Move semantics
 - Copy elision
 - More STL

Useful tools
 - Address Sanitizer
 - The Valgrind family
 - Static code analysis

Expert C ++
 - Variadic templates
 - Perfect forwarding
 - SFINAE

Concurrency
 - Threads and async
 - Mutexes

C ++ and python
 - Writing a module
 - Marrying C ++ and C
 - The ctypes module
 - The cppyy project

**Comment by hageboeck** [comment]
Wait for #63 before starting this, please.

**Comment by sponce** [comment]
I've now created a "C++BasicCourse" (see branch https://github.com/hsf-training/cpluspluscourse/tree/sponce_basicCourse). The result is a set of 217 slides (compared to 339) but I'm now wondering whether it is really needed to have a separate document, rather than just using the original set and not covering everything. To be discussed at our next meeting.
