### ISSUE TITLE
Look into creating more exercise(s) for the first day 

### ISSUE THREAD

**Issue by roiser** [hsf-training/cpluspluscourse#47]
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution.
To ensure that the right people get notified, you can tag some of the last
contributors with `@githubname`.

Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact the HSF training convenors ([contacts here](https://hepsoftwarefoundation.org/workinggroups/training.html)).

You may delete these instructions from your issue.

\- HSF Training
</details>

**Comment by hageboeck** [comment]
## Day 1
- [ ] Mention control instructions exercise in cheat sheet

## Day 2
- [ ] Writing a custom operator?
  - [ ] `+`
  - [ ] `<<` for stream
  - [ ] Functor `operator()` 
- [ ]
