### ISSUE TITLE
Mistake in modules slide?

### ISSUE THREAD

**Issue by hageboeck** [hsf-training/cpluspluscourse#487]
In the following slide, `import export module base` is probably incorrect.
(I don't find any "`import export`" on https://en.cppreference.com/w/cpp/language/modules.)

<img width="1216" alt="image" src="https://github.com/hsf-training/cpluspluscourse/assets/16205615/0045465c-b9c6-4cfe-bc96-54c3c9389721">

Presumably, the correct syntax is `import export base`, but needs to be checked.

**Comment by bernhardmgruber** [comment]
Yeah, this looks wrong. It should probably be `export import base;`.

Generally, this example looks very complicated. It may benefit from a little overhaul. I will have a look in a few days.
