### ISSUE TITLE
C++ 20 : add slides about modules

### ISSUE THREAD

**Issue by sponce** [hsf-training/cpluspluscourse#53]

**Comment by bernhardmgruber** [comment]
I have a couple of slides but not ready. I will continue after my vacation.

**Comment by bernhardmgruber** [comment]
I just reviewed the state of g++ and cmake and it still looks rather dire. cmake (3.23) still gives us no support for modules although work has progressed and support for header units is still very far out. With g++ (11 and 12) on the command line I could not yet successfully compile my [LLAMA ](https://github.com/alpaka-group/llama)unit tests with header units. I will continue a bit more, but I may reach the conclusion that it is still too difficult to teach building with modules.
