### ISSUE TITLE
Extend part about locks to shared_lock, condition_variable etc for advanced course.

### ISSUE THREAD

**Issue by hageboeck** [hsf-training/cpluspluscourse#62]

**Comment by hageboeck** [comment]
Pretty much done with this, only question that remains:
Should we go into memory order with atomics?

**Comment by bernhardmgruber** [comment]
> Pretty much done with this, only question that remains: Should we go into memory order with atomics?

I would not. Playing with memory order requires deep understanding of the C++ abstract machine (happens before, synchronizes with relationships, etc.) which well beyond the scope of a beginners or advanced course.
