### ISSUE TITLE
mention cppinsights when talking of e.g. lambdas

### ISSUE THREAD

**Issue by sponce** [hsf-training/cpluspluscourse#70]
it's useful to know what the compiler generates from a lambda function and there is a great website to look at that: https://cppinsights.io/lnk?code=I2luY2x1ZGUgPHZlY3Rvcj4KI2luY2x1ZGUgPGFsZ29yaXRobT4KCmludCBtYWluKCkKewogIHN0ZDo6dmVjdG9yPGludD4gdnsxLCAyLCAzfTsKICBpbnQgaW5jcmVtZW50ID0gNTsKICBzdGQ6OnRyYW5zZm9ybShiZWdpbih2KSwgZW5kKHYpLCBiZWdpbih2KSwKICAgIFtpbmNyZW1lbnRdKGludCB2YWx1ZSkgewogICAgICByZXR1cm4gdmFsdWUgKyBpbmNyZW1lbnQ7CiAgICB9KTsKfQ==&insightsOptions=cpp17&std=cpp17&rev=1.0
it's not just handy for lambdas, you can also check what the compilers creates for e.g. range-for

**Comment by bernhardmgruber** [comment]
This is handled by this slide?
![image](https://user-images.githubusercontent.com/1224051/182348654-44edccf9-2838-4892-bb19-fcb0e1c635fe.png)

**Comment by sponce** [comment]
Yes, that's good ! Maybe we want to have another slide on cppinsights in the tool section though, with another example ?

**Comment by bernhardmgruber** [comment]
Sure, please add a slide then! :)

**Comment by sponce** [comment]
#232 deals with this now, and with godbolt while I was at it.
