### ISSUE TITLE
Rework introductory examples of RAII

### ISSUE THREAD

**Issue by sponce** [hsf-training/cpluspluscourse#71]
from @bernhardmgruber :
the examples are too much C, people should not be reminded again that malloc, free, strncpy, FILE, fopen, fputs, fclose, EOF exist. maybe we can find a C++ version that news an array for processing some numbers, the FILE example is actually good, because it shows that C++ can do better than C here. But I am afraid that students will remember these codes as something they can use. Like we show FILE* a couple of times but never std::ifstream, so what will students remember when they need to read a file?

**Comment by chavid** [comment]
+1
