### ISSUE TITLE
Introduce a section on best practices

### ISSUE THREAD

**Issue by theanalyst** [hsf-training/cpluspluscourse#78]
Since this is a fairly generic idea, for starts we could introduce a simple slide linking to Core Guidelines (https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines). Maybe we could cherry-pick a few guidelines that are commonly considered good, for eg:
- Interfaces -I.3 (singletons) as well as I.11 & I.13 (avoid raw_ptr ownership transfer, avoid passing arrays without length)
- Errors - E.6 use RAII
- Classes - C.131 Avoid trivial getters/setters 

(Fairly opinionated list ;)

**Comment by hageboeck** [comment]
Some more ideas:
- [ ] If you have a debate about how to do something, check core guidelines
- [ ] When to use free functions (anonymous namespace) and when member functions
- [ ] Keep headers clean, low number of includes?

And on the repetition side:
- [ ] Use smart pointers
- [ ] Pass by reference

**Comment by theanalyst** [comment]
> Some more ideas:
> 
>     * [ ]  If you have a debate about how to do something, check core guidelines
Definitely. I feel like for new comers this should give some pointers on doing things in mostly correct way 
>     * [ ]  When to use free functions (anonymous namespace) and when member functions
> 
>     * [ ]  Keep headers clean, low number of includes?
:+1:

> 
> 
> And on the repetition side:
> 
>     * [ ]  Use smart pointers
>     * [ ]  Pass by reference

Yeah this would be nice, esp. understanding ownership, ie. naked pointers as a view only resource

**Comment by krasznaa** [comment]
As we discussed just now in our meeting, here are the ATLAS coding standards. Which could be pointed to, together with those of the other experiments. :wink:

http://atlas-computing.web.cern.ch/atlas-computing/projects/qa/draft_guidelines-0.2.html

**Comment by hageboeck** [comment]
Decided to make a box/design for making good practices easily recognisable, and put the good practices right next to the places where the rationales can be explained.

**Comment by bernhardmgruber** [comment]
I think we should discuss the SOLID principles at the end of the OOP chapter to give some guidance: https://en.wikipedia.org/wiki/SOLID

**Comment by hageboeck** [comment]
Closing in favour of #507
